# SPDX-FileCopyrightText: 2024 Daniel Biehl <daniel.biehl@imbus.de>
#
# SPDX-License-Identifier: Apache-2.0
extend-python-path = ["tests/DotNetDemoLibrary/bin/Debug/net8.0"]

[env]
PYTHONNET_RUNTIME = "coreclr"

[tool.robotcode-analyze.cache]
ignored-libraries = ["DotNetLibraryBase"]
